### ISSUE TITLE
Disable cursor blinking

### ISSUE THREAD

**Issue by cs-qyzhang** [inkdropapp/inkdrop-vim#28]
Please add a configuration to disable cursor blinking.

**Comment by craftzdog** [comment]
You can accomplish that by having [a custom CSS](https://docs.inkdrop.app/manual/style-tweaks) like so:

```css
.cm-fat-cursor div.CodeMirror-cursors {
    visibility: visible !important;
}
```
